Packages crud - some update
kurumeii/EcoFarm_FE pull request #30
Opened 2023-12-12 09:16 UTC by minhkoy

2023-12-12 09:36 UTC, hoanhxlyn requested changes

2023-12-12 09:36 UTC, hoanhxlyn commented on src/config/cspell/en/words.txt
@minhkoy di chuyển các từ tiếng việt sang folder vi

2023-12-12 09:36 UTC, hoanhxlyn commented on src/config/reducers/packages/index.ts
@minhkoy  sao lại để limit là 1

2023-12-12 14:25 UTC, minhkoy commented on src/config/reducers/packages/index.ts
test thôi a. E quên ch fix lại về 10
Server nếu k nhận dc ttin limit thì cũng auto để là 10

2023-12-13 04:01 UTC, hoanhxlyn approved these changes

2023-12-13 04:01 UTC, merged